require:
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/environments/*'
    - 'node_modules/**/*'
    - 'client/**/*'
    - '.bundle/**/*'

######## Style Cops
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/TrailingCommaInHashLiteral:
  Description: 'Checks for trailing comma in array and hash literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
  Enabled: true

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

######### Metrics specific
Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true
Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true
Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true
Metrics/MethodLength:
  Description: 'Avoid methods longer than 20 lines of code.'
  Max: 20
  Enabled: true
Metrics/AbcSize:
  Enabled: false